name: Continuous Integration

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: [v*]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-13, macos-12, macos-11, windows-2022, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - run: clang --version
