name: Continuous Integration

on:
  push:
    branches: ['**']

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        browser: [chrome, safari]
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: sbt test
        env:
          BROWSER: ${{ matrix.browser }}
        
