name: Continuous Integration

on:
  push:
    branches: ['**']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  PGP_SECRET: ${{ secrets.PGP_SECRET }}

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        browser: [chrome, safari]
    runs-on: macos-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check that workflows are up to date
        env:
          BROWSER: ${{ matrix.browser }}
        run: sbt test
